/*
 * Online Store
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v1/",
		Index,
	},

	Route{
		"AddShoppingCart",
		strings.ToUpper("Post"),
		"/api/v1/shoppingCarts",
		AddShoppingCart,
	},

	Route{
		"DeleteShoppingCart",
		strings.ToUpper("Delete"),
		"/api/v1/shoppingCarts",
		DeleteShoppingCart,
	},

	Route{
		"EmailChecking",
		strings.ToUpper("Post"),
		"/api/v1/email_checkers",
		EmailChecking,
	},

	Route{
		"GetProductsbyCategory",
		strings.ToUpper("Get"),
		"/api/v1/products",
		GetProductsbyCategory,
	},

	Route{
		"GetShoppingCartList",
		strings.ToUpper("Get"),
		"/api/v1/shoppingCarts",
		GetShoppingCartList,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Post"),
		"/api/v1/sessions",
		LoginUser,
	},

	Route{
		"RegisterUser",
		strings.ToUpper("Post"),
		"/api/v1/users",
		RegisterUser,
	},

	Route{
		"UploadAvatarUser",
		strings.ToUpper("Post"),
		"/api/v1/avatars",
		UploadAvatarUser,
	},
}
